name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.9, 3.11]
        exclude:
          - os: macos-latest
            python: 3.9

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: "Install poetry"
        run: python -m pip install poetry==1.8.2

      - name: "Install grasp2alm dependencies"
        run: |
          poetry export --without-hashes -o requirements.txt
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test
        run: |
          poetry install
          poetry run pytest -vv
